server:
  port: 18077
  shutdown: graceful

spring:
  application:
    name: core-api
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: ${user.timezone}
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/frame?serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
